### ISSUE TITLE
Replace Unreloader with Zeitwerk

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/roda-sequel-stack#21]
Hi Jeremy,

Was looking into this project as a template, and was wondering whether using `unreloader` made more sense in a world before `zeitwerk` became reliable outside of rails (I think it is at this point), and whether it could be proposed in the template. Or is there any other advantage to `unreloader` which is missing from any alternative?

**Comment by jeremyevans** [comment]
I'm not sure Zeitwerk supports the route file design. This is where a single class is split into multiple files, modifying a route file only reloads that route file (without unloading the class), but modifying the main class file unloads the class and then reloads the main class file and all route files.  Can Zeitwerk do that?

**Comment by HoneyryderChuck** [comment]
I assume you mean the `multi_route` plugin? If so, I guess that, given an hypothetical structure like this:

```ruby
# app.rb
class App < Roda
  plugin :multi_route
end

# app/names.rb
class App
  route('names') do |r|
    r.get do
      "names"
    end
  end
end
```

could theoretically work (at least according to the docs), given that `App` is in `app.rb`, and loading the sub-routes is roda's job. I might have to test this assumption though.

**Comment by jeremyevans** [comment]
If you can get Zeitwork to handle that, such that a modification to `app/names.rb` reloads `app/names.rb` without unloading `App`, and a modification to `app.rb` unloads `App` and then reloads `app.rb`  and `app/names.erb`, I'd be interested in switching.

**Comment by HoneyryderChuck** [comment]
Just did a small test:

```ruby
# Gemfile

 source "https://rubygems.org"

 gem "webrick"
 gem "roda"
 gem "zeitwerk"

# config.ru

require "roda"
 require 'zeitwerk'

 loader = Zeitwerk::Loader.new
 loader.logger = method(:puts)
 loader.push_dir(__dir__)

 if ENV['RACK_ENV'] == 'production'
   loader.setup
   Zeitwerk::Loader.eager_load_all
   run App
 else
   loader.enable_reloading
   loader.setup
   run ->(env) {
     loader.reload
     App.call(env)
   }
 end

# app.rb
class App < Roda
   plugin :multi_route

   require_relative "app/names"

   route do |r|
     r.multi_route

     r.root do
       'Health-check! 2'
     end

   end
 end

# app/names.rb
class App
   route("names") do |r|
     r.get do
       "names here"
     end
   end
 end
```

changes to both `app.rb` and `names.rb` got reloaded! 👌

**Comment by jeremyevans** [comment]
Does changing `app/names.rb` unload `App` and reload `app.rb`?

**Comment by HoneyryderChuck** [comment]
I'm not sure what it does internally. But if I change the payload on each file and perform the request one at a time, I see the new payload.

**Comment by jeremyevans** [comment]
From my reading of Zeitwerk's documentation (a while back), it couldn't do that.  Changing either `app.rb` or `app/names.rb` will unload `App` and reload both files.  In a large application, the difference between reloading the entire application or a single route file is huge.  If only a single route file is changed, only that route file should be reloaded.

If you want to test this, try adding a `puts __FILE__` statement at the top of both `app.rb` and `app/names.rb`, and try modifying each file separately, reloading after each modification. That way you can see when the files are actually getting reloaded.

**Comment by HoneyryderChuck** [comment]
I see what you mean. And yes you're right, both files get reloaded.

**Comment by jeremyevans** [comment]
Thanks for checking.  At this point, it looks like Zeitwerk wouldn't be a good fit for roda-sequel-stack.  If there is a way to get it to work, please let me know and I'll definitely consider it.

**Comment by fxn** [comment]
> before zeitwerk became reliable outside of rails

Let me clarify this. Zeitwerk has always been reliable outside Rails. It was designed from the start for arbitrary Ruby projects, as long as they follow the required conventions. Indeed, the first public user of Zeitwerk that I was of was `nanoc`, months before the release of Rails 6 ([commit](https://github.com/nanoc/nanoc/commit/55e1aa7174f3674f3e67836df139f81a69bf92c1)).

Zeitwerk does not support partial reloads, by design, you could get into inconsistent states. For example, If class `C` uses class `D` at the class level, and you edit `d.rb`, you cannot only reload `D`. You need to reload `C` too.

In the example above, `app/name.rb` does not even implement `App::Name`. If Roda applications follow project layout conventions except for that, you could still use Zeitwerk for the whole thing, [ignore](https://github.com/fxn/zeitwerk#ignoring-parts-of-the-project) those route files, and have custom reloading code just for them.

I remember a [question](https://github.com/fxn/zeitwerk/issues/170) about routes and Roda, but there, reloading `App` seemed OK.

I would be totally happy to help finding a minimal setup for such a mix idea if it was interesting to anyone.

**Comment by HoneyryderChuck** [comment]
> Let me clarify this. Zeitwerk has always been reliable outside Rails.

Sorry, poor choice of words from my side. I meant "more usage outside of Rails". It's a biased view probably, given that I only got wind of `zeitwerk` when it was released with `rails` (I assume most people did) and have only more recently been picking up examples for other workloads.

The scenario you suggest, ditching routes from `zeitwerk` paths while potentially implementing `unreloader` for it, is smth I was considering testing once I bootstrap the new service. I was just stressing out the possibilities, as it feels a bit wicked to use 2 reloaders for an application. But if it works, I guess it's fine. And as mentioned in the other issue, this is only an issue if the number of routes grows unwieldy, totally fine to reload a small set of them until it does not scale anymore.

Still, both great tools, thank you both. I guess there are trade-offs in everything we do, and maybe one just bumped into each other this time :)

**Comment by fxn** [comment]
> I meant "more usage outside of Rails". It's a biased view probably, given that I only got wind of zeitwerk when it was released with rails (I assume most people did) and have only more recently been picking up examples for other workloads.

No prob :), I wanted to clarify for you and for anyone reading the ticket now or in the future, but it is OK! Since Zeitwerk was released, gems started using it. It was very deliberately thought to be an autoloader for arbitrary Ruby projects, for the entire Ruby community, including regular gems and other web frameworks. Last time I checked time ago, there were more than a hundred gems loading with Zeitwerk. And nowadays, Hanami uses it too. It's truly generic.

> The scenario you suggest, ditching routes from zeitwerk paths while potentially implementing unreloader for it, is smth I was considering testing once I bootstrap the new service. I was just stressing out the possibilities, as it feels a bit wicked to use 2 reloaders for an application. But if it works, I guess it's fine. And as mentioned in the other issue, this is only an issue if the number of routes grows unwieldy, totally fine to reload a small set of them until it does not scale anymore.

If the project follows Zeitwerk conventions except for routes, off the top of my head, you could do something like this. First, put routes in a place that groups them and eases ignoring them. For example

```ruby
loader.ignore("#{__dir__}/routes")
```

Then:

```ruby
class App < Roda
  Dir["routes/**/*.rb"].each do |route_file|
    load route_file
  end
end
```

and then have a middleware that checks mtimes with this logic:

```
if all files are current
  do nothing
elsif routes have been added or modified (but not deleted), and the rest is current
  # But see comment below.
  modified_route_files.each { |route_file| load route_file }
else
  loader.reload
end
```

We special-case deletions because if you remove a route, you'd expect a request to that endpoint to fail, right? That is one of several reasons reloading doesn't just reevaluate files, it removes constants. Because if a method is removed, invocations should err.

I am not familiar with Roda (would like to!), so I don't know how far from reality is that pseudo-code, but that'd made sense off the top of my head.

Of course, if reloading performance is not an issue, eliminate the middle condition. Shopify reloads its code base on `development` mode! Zeitwerk is super lazy if not eager loading, so you only have loaded what you used anyway.

If you need any hint exploring this, please ping me, I'd be very glad to help.

**Comment by jeremyevans** [comment]
> ```ruby
> loader.ignore("#{__dir__}/routes")
> ```

@fxn would you consider something like: `loader.no_unload("#{__dir__}/routes")`, which would reload the files if there were changes, without unloading any constants?  That way you wouldn't need a hacky second reloader for the route files.

**Comment by fxn** [comment]
@jeremyevans Let's think about it:

1. Would the route files follow Zeitwerk conventions? Would `routes/names.rb` define `Routes::Names`, or `Names`? Or would just reopen `App` as in the example above?
2. If you delete a route, is Roda aware of it so that requests fail?

Note that Zeitwerk does not monitor the file system. The parent application is responsible for it, and it is responsible for calling `loader.reload` when it decides it needs to reload. It is also responsible for invoking `loader.reload` in a thread-safe manner.

Note also that Zeitwerk delegates loading to `Module#autoload`. Both for autoloading and for eager loading (an eager load is a recursive `const_get` for consistency). So all passes through `Kernel#require`.

**Comment by fxn** [comment]
My advice to Roda users to simplify things would be: If you need to special-case route files, use the current reloader. 

Otherwise, just reload everything. Zeitwerk is lazy, if you loaded 5 classes, it's only 5 classes to unload. Only to unload, you only redefine them if you use them. After a reload, you start lazy again loading nothing. `Module#autoload` is the driver.

**Comment by fxn** [comment]
Oh, that reminds me of something: The word "reload" is misleading, and I use it because it has been in the vocabulary of Rails since forever.

However, technically, unloading is just `remove_const`. If the object stored in the constant gets a ref count of 0 (which should be the case if the application is correct), the garbage collector will effectively unload. Additionally, you do not evaluate the file again, so it is not actually "reloaded" by Zeitwerk. "Reloading" (re-evaluating the file) happens only  _if_ you use the constant it defines.

**Comment by jeremyevans** [comment]
> @jeremyevans Let's think about it:
> 
> 1. Would the route files follow Zeitwerk conventions? Would `routes/names.rb` define `Routes::Names`, or `Names`? Or would just reopen `App` as in the example above?

No, Roda route files do not use a separate namespace, they reopen the class.

> 2. If you delete a route, is Roda aware of it so that requests fail?

I'm fairly sure it isn't. Route files generally represent entire branches of the routing tree, not individual routes, so it's uncommon to delete one.

> Note that Zeitwerk does not monitor the file system. The parent application is responsible for it, and it is responsible for calling `loader.reload` when it decides it needs to reload. It is also responsible for invoking `loader.reload` in a thread-safe manner.

Thank you for explaining that.  I assumed Zeitwerk did some checking of file system times, and only reloaded what it thought might have changed.

**Comment by fxn** [comment]
Yeah, so I don't really see `no_unload` in the API. Transitive dependencies are tricky, I prefer to not open that door. You just unload/reload all it was loaded, and you have full-control over when that happens, since you have to issue the call.

That's super easy to reason about, and performance is not an issue in my experience. Specially given the laziness of Zeitwerk.

**Comment by jeremyevans** [comment]
> That's super easy to reason about, and performance is not an issue in my experience.

In my experience, this is not true for medium or large Roda applications using the route file approach.  The difference between reloading the entire application (all route files) and a single routing file is huge (say 50ms compared to multiple seconds).

**Comment by fxn** [comment]
> In my experience, this is not true for medium or large Roda applications using the route file approach. The difference between reloading the entire application (all route files) and a single routing file is huge (say 50ms compared to multiple seconds).

That's interesting!
